services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=*
    restart: unless-stopped

  rag-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - PORT=7860
      - HOST=0.0.0.0
      - QDRANT_IN_MEMORY=${QDRANT_IN_MEMORY}
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data: 