version: '3.8'

services:
  rag-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=7860
      - HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped 